#!/usr/bin/env bash

i3lock \
-B=1 \
-k \
--timestr='%I:%M' \
--datestr='%A, %d %B %Y' \
--timecolor=ffffffff \
--datecolor=ffffffff \
--timesize=50 \
--datesize=20 \
--time-font=sans-serif \
--date-font=sans-serif \
--radius=150 \
--ring-width=10 \
--ringcolor=4c566aff \
--ringvercolor=81a1c1ff \
--ringwrongcolor=d08770ff \
--linecolor=000000ff \
--insidecolor=2e3440ff \
--insidevercolor=5e81acff \
--insidewrongcolor=bf616aff
